name: CI

on:
  push:
    branches: [ master ]
    tags: '*'
  pull_request:
    branches: [ master ]

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install npm packages
      run: npm install

    - name: Compile TypeScript
      run: npx tsc

    - name: Package application
      run: npm run package

